# docker compose -f docker-compose.yml -f docker-compose.prod.yml up -d
name: toasterbot

services:
  toaster:
    image: toaster:latest
    container_name: toaster
    environment:
      MONGO_USE_SRV: "true"

secrets:
  bot_token:
    file: ./Secrets/prod/bot_token
  db_cluster:
    file: ./Secrets/prod/db_cluster
  db_user:
    file: ./Secrets/prod/db_user
  db_pass:
    file: ./Secrets/prod/db_pass