name: CMake Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - windows-latest

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup CMake
        uses: lukka/get-cmake@latest

      - name: Restore vcpkg cache and install dependencies
        uses: lukka/run-vcpkg@v11
        with:
          vcpkgJsonGlob: "**/vcpkg.json"

      - name: Configure
        run: >
          cmake
          -B build
          -DCMAKE_BUILD_TYPE=Release
          -DCMAKE_TOOLCHAIN_FILE=${{ env.VCPKG_INSTALLATION_ROOT }}/scripts/buildsystems/vcpkg.cmake

      - name: Build
        run: cmake --build build --config Release --parallel

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ToasterBot-${{ matrix.os }}
          path: |
            build/ToasterBot*
            build/*.exe
            build/*.dll
            build/*.so
            build/*.dylib
